// AUTO-GENERATED by `cortextos ecosystem`. Do NOT edit by hand.
// Re-run `cortextos ecosystem` to regenerate.
//
// Note: env vars use process.env.X || 'default' so PM2 picks up the value
// from the calling shell at startup time. This means `CTX_INSTANCE_ID=foo
// pm2 restart soma-daemon` switches instances without regenerating.
module.exports = {
  apps: [
    {
      name: 'soma-daemon',
      script: "/Users/max/cortextos/dist/daemon.js",
      args: '--instance ' + (process.env.CTX_INSTANCE_ID || "default"),
      cwd: "/Users/max/cortextos",
      env: {
        CTX_INSTANCE_ID: process.env.CTX_INSTANCE_ID || "default",
        CTX_ROOT: process.env.CTX_ROOT || "/Users/max/.soma/default",
        CTX_FRAMEWORK_ROOT: "/Users/max/cortextos",
        CTX_PROJECT_ROOT: "/Users/max/cortextos",
        CTX_ORG: process.env.CTX_ORG || "solo-scale",
      },
      max_restarts: 50,
      restart_delay: 5000,
      autorestart: true,
    },
    {
      name: 'SOMA-dashboard',
      script: 'npm',
      args: 'run dev',
      cwd: "/Users/max/cortextos/dashboard",
      env: {
        PORT: process.env.PORT || '3000',
      },
      // Dashboard reads its real config from dashboard/.env.local — populated
      // by /onboarding Phase 7. PM2 just supervises the npm process.
      max_restarts: 50,
      restart_delay: 5000,
      autorestart: true,
    },
    {
      name: 'soma-jobs-worker',
      script: "/Users/max/cortextos/dist/cli.js",
      args: [
        'jobs', 'work',
        '--instance', process.env.CTX_INSTANCE_ID || "default",
        '--db', process.env.SOMA_MINIONS_DB || "/Users/max/.soma/default/minions.db",
        '--queue', process.env.SOMA_WORKER_QUEUE || 'default',
        '--concurrency', process.env.SOMA_WORKER_CONCURRENCY || '1',
        '--handlers', process.env.SOMA_WORKER_HANDLERS || 'echo,noop,sleep',
      ],
      cwd: "/Users/max/cortextos",
      env: {
        CTX_INSTANCE_ID: process.env.CTX_INSTANCE_ID || "default",
      },
      max_restarts: 50,
      restart_delay: 5000,
      autorestart: true,
    },
  ],
};
